select images by clicking on the hovering box + open image on click
beakerbrowser/dat-photos-app pull request #12
Opened 2017-12-01 22:14 UTC by mkroehnert

This is how hovering over an image looks like:

![hover](https://user-images.githubusercontent.com/7868/33505807-419bfdc2-d6ed-11e7-81f9-f43d5dccfd12.png)

And this is how a selected image looks like:
![selected](https://user-images.githubusercontent.com/7868/33505812-46d46cb6-d6ed-11e7-94b9-24aebf469db8.png)

Clicking on the image opens the dat URL of the image.

2017-12-16 18:31 UTC, mkroehnert commented
ping @taravancil

2017-12-20 18:15 UTC, taravancil requested changes
This is a good start! I'd like to see a couple of things before merging:

1. If an image is selected, the checkbox shoud remain visible even if the user is not hovering over the image.
2. The checkboxes don't match the aesthetic of the app. I'd like to see something that looks more like a checkbox. Something like this: https://codepen.io/taravancil/pen/QaEMbL

2017-12-20 18:15 UTC, taravancil commented on css/album.css
> +  border: 4px solid #009688;
I'd like to keep this transformation as it was before:

```
border: 10px solid #009688;
transform: scale(.95);
```

2017-12-20 18:15 UTC, taravancil commented on css/album.css
> +.album-images .img-container .dropdown-btn {
Let's call this something other than `.dropdown-btn` since it's not a dropdown. I think `<button class="select-btn">` would make sense.

2018-01-08 22:35 UTC, mkroehnert commented
@taravancil I finally got around to implement the requested changes.

Additionally, some thoughts on the original decisions:
* The original checkbox style was implemented to match the overlay drawn on an album on the overview page.
* The reduced thickness of the selection border was originally implemented to match the style of the share button.

2018-01-26 19:43 UTC, mkroehnert commented
@taravancil do you have any further comments?

2018-05-27 13:33 UTC, mkroehnert commented
@taravancil is there still interest in this PR from your side?

2022-01-16 16:32 UTC, closed without merging