Add a title to the top of the page and remove duplicate "Create Album" button
beakerbrowser/dat-photos-app pull request #9
Opened 2017-11-26 13:37 UTC by mkroehnert

This PR changes the following things:

An `<h1>` title element is added in the header area of the page in addition to the window title. This required removing the `display:flex` style from the header element, since this prevented center alignment of the text. Please let me know, if there is a better way to achieve the same effect.

The "Create Album" button is removed, since there is a bigger "Create Album" container on the page. This similar to other photo sites, that only have a big "Create Album" element next to all albums. In my opinion this provides a cleaner interface, but can be reverted, if requested.

2017-11-26 13:52 UTC, mkroehnert commented
I just realized, that the CSS change breaks the header of the album page. This should be resolved before considering a merge.

2017-11-26 14:02 UTC, mkroehnert commented
The CSS issue is now fixed by adding `flex-basis: 100%` to the style of the `<h1>` tag in the header.

2017-11-28 15:25 UTC, taravancil requested changes

2017-11-28 15:25 UTC, taravancil commented on index.html
> +    <title>Photo Gallery</title>
I prefer sentence case, so let's leave this how it was.

2017-11-28 15:25 UTC, taravancil commented on index.html
> -      <button class="create-album btn primary">Create album +</button>
I'd like to keep the "Create album" button in the header.  I like having a header in each view that has a primary action button in the same spot.

2017-11-28 15:25 UTC, taravancil commented on js/index.js
> +  function setTitle (title) {
This isn't necessarily needed since the`<h1 class="gallery-title"></h1>` won't be merged in, but let's keep it since we might use it later on.

2017-11-28 15:25 UTC, taravancil commented on css/header.css
> +header h1 {
Let's remove this (see comments below)

2017-11-28 20:48 UTC, mkroehnert commented
Changed, although having duplicate buttons with the same functionality is in my opinion confusing the interface.
After the requested changes, the `setTitle` function remains.

2017-11-28 20:53 UTC, taravancil commented
The beautiful thing about Beaker and p2p apps is that no one app has to satisfy the preferences of every user! We can all customize the apps we use and they can still remain compatible with each other 🙂

2017-11-29 15:55 UTC, merged